id: P06864081
initial_creation_type: input
source_metadata:
  title: Jamyang Khyenrab Tayé Series
  language: en
  description: 'Texts by and about Jamyang Khyenrab Tayé (''jam dbyangs mkhyen rab
    mtha’ yas, 1862–1937):'
  volume:
    de30cf16a0564ddda67ecc1357a53d52:
      title: 'The Fresh Utpala: A Prayer to the Great Learned Teacher and Vajra-Holder
        Jamyang Khyenrab Tayé'
      parent: Prayers
    fdc897ec023a4bc3a616f555f174179e:
      title: Prayer for the Swift Rebirth of Jamyang Khyenrab Tayé
      parent: Swift Rebirth Prayers
created_at: '2022-02-28T23:34:29.573814'
last_modified_at: '2022-02-28T23:34:29.573820'
